# Generated by Django 5.2.1 on 2026-03-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('proj_notes', models.TextField()),
                ('papers', models.TextField()),
            ],
        ),
    ]
